# ansible-pull setup
#
# on remote hosts, set up ansible to run periodically using the latest code
# from a particular checkout, in pull based fashion, inverting Ansible's
# usual push-based operating mode.
#
# This particular pull based mode is ideal for:
#
# (A) massive scale out
# (B) continual system remediation
#
# DO NOT RUN THIS AGAINST YOUR HOSTS WITHOUT CHANGING THE repo_url
# TO SOMETHING YOU HAVE PERSONALLY VERIFIED
#
#
---
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
  - name: print variables
    ansible.builtin.debug:
      msg: "Hola!!!!"
  - name: print variables
    ansible.builtin.debug:
      msg: "Adios!!!!"
  - name: print variables
    ansible.builtin.debug:
      msg: "Adios!!!!"
